spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    hibernate:
      hbm2ddl:
        delimiter: ';'
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: create
  datasource:
    url: jdbc:postgres://localhost:5432/pesquisa
    username: root

